export const mainItemsData = [
  {
    image: "/venue-1.jfif",
    title: "Cloud Spaces - Circle Mall",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    area: 78.999,
    persons: 40,
    rating: 4.5,
  },
  {
    image: "/venue-2.jfif",
    title: "WO-RK by The Co-Spaces",
    location: "Baniyas Rd - Deira - Al Rigga - Dubai - United Arab Emirates",
    area: 987.923,
    persons: 1400,
    rating: 4.5,
  },
  {
    image: "/venue-3.jfif",
    title: "Le Bistro by Salmontini DIFC",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    area: 78.999,
    persons: 40,
    rating: 4.5,
  },
  {
    image: "/main-venue-4.jfif",
    title: "Nightjar - City Walk",
    location: "Baniyas Rd - Deira - Al Rigga - Dubai - United Arab Emirates",
    area: 159.999,
    persons: 150,
    rating: 4.5,
  },
  {
    image: "/main-venue-5.jfif",
    title: "The LoLo House",
    location: "Al Mankhool - Dubai - United Arab Emirates",
    area: 87.923,
    persons: 40,
    rating: 4.5,
  },
  {
    image: "/main-venue-6.jfif",
    title: "Entrepreneurship Hub by du Bus...",
    location: "Casablanca Road - Al Garhoud - Dubai - United Arab Emirates",
    area: 151.593,
    persons: 100,
    rating: 4.5,
  },
];
