export const servicesVenuesData = [
  {
    image: "/service-1.jpg",
    title: "Sweet Sentiments",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-2.jpg",
    title: "Lilac Morning",
    location: "Baniyas Rd - Deira - Al Rigga - Dubai - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-3.jpg",
    title: "Heaven's Secret",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-4.jpg",
    title: "The Royal Garden",
    location: "Baniyas Rd - Deira - Al Rigga - Dubai - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-5.jpg",
    title: "The LoLo House",
    location: "Al Mankhool - Dubai - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-6.jpg",
    title: "Sweet Indulgence",
    location: "Casablanca Road - Al Garhoud - Dubai - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-1.jpg",
    title: "Sweet Sentiments",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-2.jpg",
    title: "Lilac Morning",
    location: "Baniyas Rd - Deira - Al Rigga - Dubai - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
  {
    image: "/service-3.jpg",
    title: "Heaven's Secret",
    location: "Corniche Road East - Abu Dhabi - United Arab Emirates",
    rating: 4.5,
    price: 150.0,
  },
];
